<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default scorecard</name>
  <uuid>de44d530-21df-4610-a5b6-cd25282ddb34</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'ML model invocation' is in error 
then
set decision to a new Scoreboard where 
	the Confidence is 0 , 
	the Segment is "Unknown" , 
	High risk is true ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
