<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get machine learning output</name>
  <uuid>0608f42f-17a1-4376-b547-2c739f78ba8d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set percent to the maximum score of 'ML model invocation';
if the predictions of 'ML model invocation' is 1
then
set decision  to a new Scoreboard where 
	the Confidence is percent , 
	the Segment is "Unknown" , 
	High risk is true; 
else
set decision  to a new Scoreboard where 
	the Confidence is percent , 
	the Segment is "Unknown" , 
	High risk is false;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
